### ISSUE TITLE
fail to unify/intersect two circle and one rectangle

### ISSUE THREAD

**Issue by wsarsenic** [alexbol99/flatten-boolean-op#6]
It failts to unify/intersect  two circle and one rectangle.
there is no item in face of poly2.

As for the intersection case, replace the last two sentences with:
let poly = unify(circle1, circle2);
let poly2 = intersect(poly, polygon1);

here is the code:
let ratio = 1000.0
    let r1 = 5
    let r2 = 10
    let r = 1.0

    r1 /= ratio
    r2 /= ratio

    let polygon1 = new Polygon();
    polygon1.addFace([point(0.05945262438793066,0.14368740465695018), point(0.10114386438793067,0.08830964465695021),
    point(0.10913291561206932, 0.0943242153430498 ), point(0.06744167561206932, 0.1497019753430498 )]);

    let circle1 = new Polygon();
    circle1.addFace([arc(point(0.06444813, 0.1461997), r2, 0, 2*Math.PI, false)]);

    let circle2 = new Polygon();
    circle2.addFace([arc(point(0.10558622, 0.09010236), r2, 0, 2*Math.PI, false)]);

    let poly = unify(circle1, polygon1);
    let poly2 = unify(poly, circle2);

**Comment by alexbol99** [comment]
Hello @wsarsenic ,

All polygon faces in unify operation should have same orientation: clockwise or counterclockwise.
You can ensure them to be same orientation (for example, clockwise) in the following way:
```
let polygon1 = new Polygon();
let face1 = polygon1.addFace([point(0.05945262438793066,0.14368740465695018), point(0.10114386438793067,0.08830964465695021),
point(0.10913291561206932, 0.0943242153430498 ), point(0.06744167561206932, 0.1497019753430498 )]);
if (face1.orientation() !== Flatten.ORIENTATION.CW) {
    face1.reverse();
 }
```
Note, you don't need this check for circles, because  the last parameter in arc creator is orientation, where ```false``` already means ```clockwise```

After you reorder your polygons, the result of the operation will we fine, see this notebook:
https://observablehq.com/d/1867a42f27281a8a

Thank you for cooperation,
Alex Bol

**Comment by wsarsenic** [comment]
It works. Thank you!
